# Generated by Django 5.0.12 on 2025-02-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyect',
            name='problem',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='versionproyect',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='versionproyect',
            name='problem',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='versionproyect',
            name='promt',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AlterField(
            model_name='proyect',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
