# Generated by Django 5.0.12 on 2025-02-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0002_proyect_problem_versionproyect_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionrequerimientos',
            name='promt',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='versiontask',
            name='promt',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='versionuserhistory',
            name='promt',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
    ]
