# Generated by Django 5.0.12 on 2025-02-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0003_versionrequerimientos_promt_versiontask_promt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyect',
            name='promt',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
    ]
