# Generated by Django 5.0.12 on 2025-02-27 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0004_proyect_promt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proyect',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requerimientos',
            name='proyect',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_documents.proyect'),
        ),
        migrations.AddField(
            model_name='task',
            name='user_history',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_documents.userhistory'),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='requerimientos',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_documents.requerimientos'),
        ),
    ]
