# Generated by Django 5.0.12 on 2025-03-24 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0005_proyect_user_requerimientos_proyect_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='requerimientos',
            old_name='proyect',
            new_name='project',
        ),
        migrations.RenameModel(
            old_name='Proyect',
            new_name='Project',
        ),
        migrations.CreateModel(
            name='VersionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('promt', models.CharField(blank=True, max_length=2555, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('problem', models.CharField(blank=True, max_length=2555, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_documents.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='VersionProyect',
        ),
    ]
